// Copyright 2011, Dave Coffin
// Use JDK 1.5 or later and have Oracle ojdbc5.jar or later on client classpath

// From Chapter 11

package testojs;

import java.io.Serializable;

import java.sql.ResultSet;
import java.sql.Statement;

import oracle.jdbc.OracleCallableStatement;
import oracle.jdbc.OracleConnection;
import oracle.jdbc.OracleResultSet;
import oracle.jdbc.OracleTypes;

import oracle.sql.RAW;

import orajavsec.OracleJavaSecure;
import orajavsec.RevLvlClassIntfc;

public class TestOracleJavaSecure {
    // Pass this class to Oracle for Application Authentication
    // Update rev level and store in Oracle
    // Remove old rev level class from Oracle to invalidate old code
    public static class AnyNameWeWant
        implements Serializable, RevLvlClassIntfc
    {
        // Structure and name (package and outer class) equal to application
        // Name difference - ClassNotFoundException
        // Structure difference - InvalidClassException
        private static final long serialVersionUID = 2011013100L;
        private String innerClassRevLvl = "20110131a";
        //private String innerClassRevLvl = "20110131b";
        //private String innerClassRevLvl = "20110131c";
        public String getRevLvl() {
            return innerClassRevLvl;
        }
    }

    public static void main( String[] args ) {
        OracleCallableStatement stmt = null;
        Statement mStmt = null;
        ResultSet rSet;
        try {
            // Submit 2-Factor auth code on command line, once received
            String twoFactorAuth = "";
            if( args.length != 0 && args[0] != null ) twoFactorAuth = args[0];
            String applicationID = "HRVIEW";
            Object appClass = new AnyNameWeWant();

            OracleJavaSecure.setAppContext( applicationID, appClass, twoFactorAuth );

            OracleJavaSecure.getAppConnections();

            if( twoFactorAuth.equals( "" ) ) {
                // This message is already generated by OrcleJavaSecure
                //System.out.println( "Call again with 2-Factor code parameter" );
                return;
            }

            // Demonstrate copy connsHash from previous version
            // Only do this once, make sure it worked (see appsec.V_APP_CONN_REGISTRY),
			// then comment this line
            //OracleJavaSecure.copyAppConnections( "20110131a" );
            // Get copied list of connection strings for new version number
            OracleJavaSecure.getAppConnections();

            OracleJavaSecure.putAppConnString( "Orcl", "appusr",
                "password", "localhost", String.valueOf( 1521 ) );
            //Only do this line once -- must be admin account
            OracleJavaSecure.putAppConnections();

            OracleConnection conn = OracleJavaSecure.getAAConnRole( "orcl", "appusr" );

			// If we provided an old or wrong twoFactorAuth,
            //  will get "no data found" errors above and null pointer here
            try {
                mStmt = conn.createStatement();
            } catch( NullPointerException n ) {
                System.out.println( "Wrong or old 2-Factor code parameter" );
                return;
            }

            rSet = mStmt.executeQuery( "SELECT SYS_CONTEXT( 'USERENV', 'OS_USER' )," +
            "SYS_CONTEXT( 'USERENV', 'PROXY_USER' ),SYS_CONTEXT( 'USERENV', 'IP_ADDRESS' ),"+
            "SYS_CONTEXT( 'USERENV', 'SESSION_USER' ),SYS_CONTEXT( 'USERENV', 'CLIENT_IDENTIFIER' ) FROM DUAL" );
            if ( rSet.next() ) {
                System.out.println( rSet.getString( 1 ) );
                System.out.println( rSet.getString( 2 ) );
                System.out.println( rSet.getString( 3 ) );
                System.out.println( rSet.getString( 4 ) );
                System.out.println( rSet.getString( 5 ) );
            }
            rSet = mStmt.executeQuery( "SELECT * FROM sys.session_roles" );
            if ( rSet.next() ) {
                System.out.println( rSet.getString( 1 ) );
            }

            int errNo;
            String errMsg;

            String locModulus = OracleJavaSecure.getLocRSAPubMod();
            String locExponent = OracleJavaSecure.getLocRSAPubExp();

            stmt = ( OracleCallableStatement )conn.prepareCall(
                "CALL hr.hr_sec_pkg.p_select_employees_sensitive(?,?,?,?,?,?,?,?,?)" );
            stmt.registerOutParameter( 3, OracleTypes.RAW );
            stmt.registerOutParameter( 4, OracleTypes.RAW );
            stmt.registerOutParameter( 5, OracleTypes.RAW );
            stmt.registerOutParameter( 6, OracleTypes.RAW );
            stmt.registerOutParameter( 7, OracleTypes.CURSOR );
            stmt.registerOutParameter( 8, OracleTypes.NUMBER );
            stmt.registerOutParameter( 9, OracleTypes.VARCHAR );
            stmt.setString( 1, locModulus );
            stmt.setString( 2, locExponent );
            stmt.setNull(   3, OracleTypes.RAW );
            stmt.setNull(   4, OracleTypes.RAW );
            stmt.setNull(   5, OracleTypes.RAW );
            stmt.setNull(   6, OracleTypes.RAW );
            stmt.setInt(    8, 0 );
            stmt.setNull(   9, OracleTypes.VARCHAR );
            stmt.executeUpdate();

            errNo = stmt.getInt( 8 );
            if( errNo != 0 ) {
                errMsg = stmt.getString( 9 );
                System.out.println( "Oracle error 2) " + errNo +
                    ", " + errMsg );
            } else {
                System.out.println( "Oracle success 2)" );
                OracleResultSet rs = ( OracleResultSet )stmt.getCursor( 7 );
                //while( rs.next() ) {
                // Only show first row
                if( rs.next() ) {
                    System.out.print( rs.getString( 1 ) );
                    System.out.print( ", " );
                    System.out.print( rs.getString( 2 ) );
                    System.out.print( ", " );
                    System.out.print( rs.getString( 3 ) );
                    System.out.print( ", " );
                    System.out.print( rs.getString( 4 ) );
                    System.out.print( ", " );
                    System.out.print( rs.getString( 5 ) );
                    System.out.print( ", " );
                    System.out.print( rs.getString( 6 ) );
                    System.out.print( ", " );
                    System.out.print( rs.getString( 7 ) );
                    System.out.print( ", " );
                    System.out.print( OracleJavaSecure.getDecryptData(
                        rs.getRAW( 8 ), stmt.getRAW( 6 ),
                        stmt.getRAW( 5 ), stmt.getRAW( 3 ),
                        stmt.getRAW( 4 ) ) );
                    System.out.print( ", " );
                    System.out.print( OracleJavaSecure.getDecryptData(
                        rs.getRAW( 9 ), stmt.getRAW( 6 ),
                        stmt.getRAW( 5 ), stmt.getRAW( 3 ),
                        stmt.getRAW( 4 ) ) );
                    System.out.print( ", " );
                    System.out.print( rs.getString( 10 ) );
                    System.out.print( ", " );
                    System.out.print( rs.getString( 11 ) );
                    System.out.print( "\n" );
                }
                if( null != rs ) rs.close();
                if( null != stmt ) stmt.close();
            }
            OracleJavaSecure.closeConnection();
        } catch( Exception x ) {
            System.out.println( "Local Exception:" );
            x.printStackTrace();
        }
        System.exit( 0 );
    }
}

/*
apver
=====
CREATE USER oranonadm IDENTIFIED EXTERNALLY;
GRANT create_session_role TO oranonadm;
ALTER USER oranonadm GRANT CONNECT THROUGH appver;



orcl
=====
CREATE USER oranonadm IDENTIFIED EXTERNALLY;
GRANT create_session_role TO oranonadm;
ALTER USER oranonadm GRANT CONNECT THROUGH appusr;

orcl/hr
=======
INSERT INTO employees
    (employee_id, first_name, last_name, email, phone_number, hire_date,
    job_id, salary, commission_pct, manager_id, department_id)
VALUES
    (employees_seq.NEXTVAL, 'First', 'Last', 'ORANONADM',
    '800.555.1212', SYSDATE, 'SA_REP', 5000, 0.20, 147, 80);

COMMIT;

select employee_id from employees where email='ORANONADM';

INSERT INTO hr.v_emp_mobile_nos
    ( employee_id, user_id, com_pager_no, sms_phone_no, sms_carrier_cd )
    VALUES ( (select employee_id from employees where email='ORANONADM'),
      'ORANONADM', '12345', '8005551212', 'Verizon' );

COMMIT;

select * from hr.v_emp_mobile_nos where user_id = 'ORANONADM';

without put app conns call

C:\dev\mywork\OraJavSecure\Chapter11>java testojs.TestOracleJavaSecure 6710-8651
-6617
Domain: ORGDOMAIN, Name: ORANONADM
Domain: ORGDOMAIN, Name: ORANONADM
oranonadm
APPUSR
127.0.0.1
ORANONADM
ORANONADM
HRVIEW_ROLE
Oracle success 2)
303, D, C, D.COFFIN, 800.555.1212, 2011-06-11 22:51:55, SA_REP, 5000, .2, 147, 8
0

C:\dev\mywork\OraJavSecure\Chapter11>


with admin put app conns call

C:\dev\mywork\OraJavSecure\Chapter11>java testojs.TestOracleJavaSecure 6710-8651
-6617
Domain: ORGDOMAIN, Name: ORANONADM
java.sql.SQLException: ORA-06550: line 1, column 13:
PLS-00201: identifier 'APPSEC.APPSEC_ADMIN_PKG' must be declared
ORA-06550: line 1, column 7:
PL/SQL: Statement ignored



SQL> select * from appsec.v_two_fact_cd_cache;

EMPLOYEE_ID APPLICATION_ID           TWO_FACTOR_CD
----------- ------------------------ ------------------------
IP_ADDRESS                                    DISTRIB_CD CACHE_TS
--------------------------------------------- ---------- ---------
        304 HRVIEW                   6710-8651-6617
127.0.0.1                                              0 11-JUN-11

        300 HRVIEW                   4310-9175-1987
127.0.0.1                                              0 11-JUN-11


SQL>



C:\dev\mywork\OraJavSecure\Chapter11>javac testojs/TestOracleJavaSecure.java

C:\dev\mywork\OraJavSecure\Chapter11>java testojs.TestOracleJavaSecure
Domain: ORGDOMAIN, Name: ORANONADM
Please rerun with 2-Factor Auth Code!
Please rerun with 2-Factor Auth Code!

C:\dev\mywork\OraJavSecure\Chapter11>java testojs.TestOracleJavaSecure 123
Domain: ORGDOMAIN, Name: ORANONADM
Oracle error 21) 100, ORA-01403: no data found
Oracle error 21) 100, ORA-01403: no data found
Wrong or old 2-Factor code parameter

C:\dev\mywork\OraJavSecure\Chapter11>java testojs.TestOracleJavaSecure 8112-8114
-7408
Domain: ORGDOMAIN, Name: ORANONADM
Oracle error 21) 100, ORA-01403: no data found
Oracle error 21) 100, ORA-01403: no data found
Wrong or old 2-Factor code parameter

C:\dev\mywork\OraJavSecure\Chapter11>java testojs.TestOracleJavaSecure
Domain: ORGDOMAIN, Name: ORANONADM
Please rerun with 2-Factor Auth Code!
Please rerun with 2-Factor Auth Code!

C:\dev\mywork\OraJavSecure\Chapter11>java testojs.TestOracleJavaSecure 2747-4367
-3056
Domain: ORGDOMAIN, Name: ORANONADM
Domain: ORGDOMAIN, Name: ORANONADM
oranonadm
APPUSR
127.0.0.1
ORANONADM
ORANONADM
HRVIEW_ROLE
Oracle success 2)
303, D, C, D.COFFIN, 800.555.1212, 2011-06-11 22:51:55, SA_REP, 5000, .2, 147, 8
0

C:\dev\mywork\OraJavSecure\Chapter11>

===========================================================================
C:\dev\mywork\OraJavSecure\Chapter11>javac testojs/TestOracleJavaSecure.java

C:\dev\mywork\OraJavSecure\Chapter11>java testojs.TestOracleJavaSecure
Domain: ORGDOMAIN, Name: OSUSER
Please rerun with 2-Factor Auth Code!
java.lang.NullPointerException
Please rerun with 2-Factor Auth Code!

C:\dev\mywork\OraJavSecure\Chapter11>java testojs.TestOracleJavaSecure 123
Domain: ORGDOMAIN, Name: OSUSER
Oracle error 21) 100, ORA-01403: no data found
java.lang.NullPointerException
Oracle error 21) 100, ORA-01403: no data found
Wrong or old 2-Factor code parameter

C:\dev\mywork\OraJavSecure\Chapter11>sqlplus sys@apver as sysdba

SQL*Plus: Release 11.2.0.1.0 Production on Sun Jun 12 20:24:16 2011

Copyright (c) 1982, 2010, Oracle.  All rights reserved.

Enter password:

Connected to:
Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - 64bit Production
With the Partitioning, OLAP, Data Mining and Real Application Testing options

SQL> select * from appsec.v_two_fact_cd_cache;

EMPLOYEE_ID APPLICATION_ID           TWO_FACTOR_CD
----------- ------------------------ ------------------------
IP_ADDRESS                                    DISTRIB_CD CACHE_TS
--------------------------------------------- ---------- ---------
        304 HRVIEW                   2747-4367-3056
127.0.0.1                                              0 12-JUN-11

        300 HRVIEW                   3471-8557-5210
127.0.0.1                                              0 12-JUN-11


SQL> exit
Disconnected from Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - 64
bit Production
With the Partitioning, OLAP, Data Mining and Real Application Testing options

C:\dev\mywork\OraJavSecure\Chapter11>java testojs.TestOracleJavaSecure 3471-8557
-5210
Domain: ORGDOMAIN, Name: OSUSER
Domain: ORGDOMAIN, Name: OSUSER
OSUSER
APPUSR
127.0.0.1
OSUSER
OSUSER
HRVIEW_ROLE
Oracle success 2)
303, D, C, D.COFFIN, 800.555.1212, 2011-06-11 22:51:55, SA_REP, 5000, .2, 147, 8
0

C:\dev\mywork\OraJavSecure\Chapter11>


C:\dev\mywork\OraJavSecure\Chapter11>javac testojs/TestOracleJavaSecure.java

C:\dev\mywork\OraJavSecure\Chapter11>java testojs/TestOracleJavaSecure
Domain: ORGDOMAIN, Name: ORANONADM
Please rerun with 2-Factor Auth Code!
java.sql.SQLException: ORA-06550: line 1, column 13:
PLS-00201: identifier 'APPSEC.APPSEC_ADMIN_PKG' must be declared
ORA-06550: line 1, column 7:
PL/SQL: Statement ignored
*/
